client: src/interface.cpp src/client.cpp
	g++ -std=c++20 -I include/ src/interface.cpp src/statistics.cpp src/client.cpp -o client

server: src/server.cpp
	g++ -std=c++20 -I include/ src/server.cpp -o server
